services:
  app:
    build: .
    container_name: katalog-buku-api
    ports:
      - "3000:3000"
    volumes:
      # Persist file SQLite agar data tidak hilang saat container restart
      - sqlite_data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_PATH=/app/data/books.db
    restart: unless-stopped

volumes:
  sqlite_data:
