name: CD - Deploy ke Debian Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Deploy langsung di server
        run: |
          set -e
          cd /var/www/RESTful-API-PPL-Katalog-Buku
          git pull origin main
          docker compose down
          docker compose up -d --build
          echo "Deployment berhasil! API berjalan di port 3000."